//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources
{
    using System;

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;
        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ratushniak_JewelryStore.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        public static global::System.Globalization.CultureInfo Culture
        {
            get { return resourceCulture; }
            set { resourceCulture = value; }
        }

        public static string Home
        {
            get { return ResourceManager.GetString("Home", resourceCulture); }
        }
        public static string Catalog
        {
            get { return ResourceManager.GetString("Catalog", resourceCulture); }
        }
        public static string Categories
        {
            get { return ResourceManager.GetString("Categories", resourceCulture); }
        }
        public static string Name
        {
            get { return ResourceManager.GetString("Name", resourceCulture); }
        }
        public static string Type
        {
            get { return ResourceManager.GetString("Type", resourceCulture); }
        }
        public static string Material
        {
            get { return ResourceManager.GetString("Material", resourceCulture); }
        }
        public static string Weight
        {
            get { return ResourceManager.GetString("Weight", resourceCulture); }
        }
        public static string Price
        {
            get { return ResourceManager.GetString("Price", resourceCulture); }
        }
        public static string Category
        {
            get { return ResourceManager.GetString("Category", resourceCulture); }
        }
        public static string Buy
        {
            get { return ResourceManager.GetString("Buy", resourceCulture); }
        }
        public static string Filter
        {
            get { return ResourceManager.GetString("Filter", resourceCulture); }
        }
        public static string Reset
        {
            get { return ResourceManager.GetString("Reset", resourceCulture); }
        }
        public static string AllCategories
        {
            get { return ResourceManager.GetString("AllCategories", resourceCulture); }
        }
        public static string ShopName
        {
            get { return ResourceManager.GetString("ShopName", resourceCulture); }
        }
        public static string AboutShop
        {
            get { return ResourceManager.GetString("AboutShop", resourceCulture); }
        }
        public static string Contacts
        {
            get { return ResourceManager.GetString("Contacts", resourceCulture); }
        }
        public static string WorkHours
        {
            get { return ResourceManager.GetString("WorkHours", resourceCulture); }
        }
        public static string Rights
        {
            get { return ResourceManager.GetString("Rights", resourceCulture); }
        }
        public static string Language
        {
            get { return ResourceManager.GetString("Language", resourceCulture); }
        }
    }
}